# Specifify a base image
FROM node:16-alpine

# Create a working directory 
WORKDIR /app

# Run a series of commands
COPY ./package.json .
RUN npm install 
COPY . . 

# Run a startup command
CMD ["npm", "run", "start"]